spring:
  application:
    name: hello-server

server:
  port: 8071

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka,http://discovery2:8762/eureka
  instance:
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}