#zuul:
#  prefix: /api
#  routes:
#    hello-server:
#      path: /server/**
#      url: http://localhost:8071
#    hello-client:
#      path: /client/**
#      serviceId: HELLO-CLIENT

#zuul:
#  routes:
#    localhost:
#      path:/zuul/**
#      url:http://localhost:8079
  
---
zuul:    
  host:
    socket-timeout-millis: 150000
    connect-timeout-millis: 150000
    max-total-connections: 200
    max-per-route-connections: 100
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      url: http://localhost:8071
    hello-client:
      path: /client/**
      serviceId: HELLO-CLIENT

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery1:8761/eureka,http://discovery2:8762/eureka
    registerWithEureka: false
  instance:
    hostname: localhost

server:
  port: 8079

spring:
  application:
    name: zuul-service

routeRefresh:
  time: 1
  
filter:
  groovy:
    path: src/main/resources/META-INF/filter/
    refreshTime: 10
    
    
---
## 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://csj.nhsoft.cn:3306/zuul?useUnicode=true&characterEncoding=GBK&useSSL=false
    username: root
    password: cSfwLEMPaZUCrGNTkIH5

jdbc:
  maxPoolSize: 600
  minPoolSize: 10
  initialPoolSize: 10
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  validationQuery: SELECT 'x'
  testWhileIdle: true
  testOnBorrow: false
  testOnReturn: false
  filters: stat,wall,slf4j



## Mybatis 配置
mybatis:
  typeAliasesPackage: io.spring2go.zuul.route.model
  mapperLocations: classpath:mapper/*.xml
  configuration.cache-enabled: true